 export const cryptos=[
    {
        id:1,
        name:"BTC",
        subname:"Bitcoin",
        logo:require('./assets/bitcoin.png'),
        price:'$35,787.42',
        percentage:'-6.27%',
        color:'red',
    },
    {
        id:2,
        name:"USDT",
        subname:"TetherUs",
        logo:require('./assets/usdt.png'),
        price:'$0.99993',
        percentage:'+2.24%',
        color:'green',
    },
    {
        id:3,
        name:"ETH",
        subname:"Etherium",
        logo:require('./assets/Eth.png'),
        price:'$2,532.84',
        percentage:'-1.5%',
        color:'red',
    },
    ];